package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, November 14, 2019 8:14:07 PM PST
*/

public interface HelloOperations 
{
  String judgeInt (String inStr);
  String sum_func (String inStr);
  String func_cal ();
  void shutdown ();
} // interface HelloOperations
